name: audio_conditioned_unet

channels:
  - pytorch
  - defaults

dependencies:
  - python=3.7
  - Cython==0.28.3
  - matplotlib==2.2.2
  - numpy==1.16.4 
  - pytorch=1.5.1
  - scipy==1.1.0
  - torchvision=0.6.1
  - tqdm==4.32.1

  - pip:
    - madmom==0.16.1 
    - opencv_python==3.4.3.18
    - pysoundfile==0.9.0.post1
    - pyfluidsynth==1.2.5
    - scikit-learn==0.21.3
    - pyyaml==5.3.1
    - tensorboard==2.0.0

