
spectrogram_params: {'sample_rate': 22050, 'frame_size': 2048, 'fps': 20, 'pad': 40}
gt_width: 10

real_perf: False
tempo_factors: [500, 750, 950, 1000, 1050, 1250, 1500]

sf_path: 'sound_fonts/grand-piano-YDP-20160804.sf2'

